---
version: '3.8'

services:
  db:
    ports:
      - "3306:3306"

  app:
    ports:
      - "8080:8080"
    volumes:
      # ディレクトリ全体ではなく、コンパイルが必要なソースコードのみをマウントする
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
    # DockerfileのCMDを上書きし、DevToolsが変更を検知できるようにする
    command: ["./wait-for-it.sh", "db", "3306", "--", "mvn", "spring-boot:run",]

  front:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node.modules # ホストPCのnode.modulesファイルで上書しないように
    command: yarn dev --host # --host: コンテナは別環境になるため明示的に外部(ホストPC)からの接続を許可するためのもの