---
- name: Configure Ubuntu VM for Refrigerator App
  hosts: vm_server
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache and install prerequisites
      ansible.builtin.apt: # `apt` を操作するためのモジュール
        name: ['ca-certificates', 'curl']
        state: present # もしインストールされていなければインストールし、既にインストールされていれば何もしない
        update_cache: yes

    - name: Download Docker install script
      ansible.builtin.get_url: # 指定したURLからファイルをダウンロードする
        url: https://get.docker.com #Dockerのスクリプトファイル
        dest: /tmp/get-docker.sh # ダウンロードしたファイルを保存する場所(/tmoは一時ファイル保管場所)
        mode: '0755' #権限設定

    - name: Run Docker install script
      ansible.builtin.command: #コマンド実行タスク
        cmd: /tmp/get-docker.sh #ダウンロードしたファイル実行
        creates: /usr/bin/docker #'creates'で指定したファイルが存在する場合は'command'タスクは実行されない

    - name: Ensure Docker service is running and enabled
      ansible.builtin.systemd:
        name: docker #/usr/bin/Dockerのこと
        state: started #startにしないように
        enabled: yes

    - name: Add 'jsaka' user to docker group
      ansible.builtin.user:
        name: jsaka #捜査対象のユーザーを決める
        groups: docker #所属するグループを決める
        append: yes #グループの所属はappendにすること(state: presentだとそのグループにしか所属しなくなる→sudo使えない)